#!/bin/bash

source hyperdata_commamd.cfg

kubectl exec -n $NAMESPACE $(kubectl get po -n $NAMESPACE | grep $HD_NAME) -i -- /bin/bash -c 'source ~/.bashrc \
&& stopServer -host localhost:49736 -u jeus -p jeus; \
stopServer -host localhost:19736 -u jeus -p jeus; \
stopServer -host localhost:29736 -u jeus -p jeus; \
stopServer -host localhost:9736 -u jeus -p jeus'

kubectl exec -n $NAMESPACE $(kubectl get po -n $NAMESPACE | grep $HD_NAME) -it -- /bin/bash -c 'source ~/.bashrc && jeusadmin -u jeus -p jeus server-info && ps -ef | grep -m 1 spring'


